-- FUNCIONES ESCALARES
/*
SON FUNCIONES QUE SE CARACTERIZAN POR OPERAR SOBRE UN VALOR Y DESPUÉS DEVOLVER OTRO VALOR.
LAS FUNCIONES ESCALARES SE PUEDEN UTILIZAR DONDE LA EXPRESIÓN SEA VÁLIDA
*/
-- 1 FUNCIONES DE CONFIGURACIÓN
	-- MUESTRA EL NOMBRE DEL SERVIDOR
	SELECT @@SERVERNAME;
	-- MUESTRA EL IDIOMA CONFIGURADO EN EL SERVIDOR
	SELECT @@LANGUAGE;
	-- MUESTRA EL NOMBRE DE LA INSTANCIA DEL SERVIDOR SQL
	SELECT @@SERVICENAME;
	-- MUESTRA LA VERSIÓN DE SQL SERVER ACTUAL
	SELECT @@VERSION;



-- 2 FUNCIONES DE CONVERSIÓN  - CONVERT - CAST
	-- CONVERT
	DECLARE @CANTIDAD INT;
	SET @CANTIDAD = (SELECT COUNT(*) FROM Administrativo.DBO.Habitante);
	SELECT CONVERT(CHAR(10),@CANTIDAD);

	---
	DECLARE @VAR VARCHAR(10) = '10HOLA'
	DECLARE @NUMERO INT = LEFT(@VAR,2)
	SELECT @NUMERO + 1
		SELECT SQL_VARIANT_PROPERTY(@numero,'BaseType')
	-- CAST
	DECLARE @CANTIDAD2 CHAR(10);
	SET @CANTIDAD2 = (SELECT COUNT(*) FROM Administrativo.DBO.Habitante);
	SELECT CAST(@CANTIDAD2 AS INT);
	-- MOSTRAR EL TIPO DE DATO
	SELECT SQL_VARIANT_PROPERTY(@CANTIDAD2,'BaseType')


	USE administrativo
	SELECT * FROM Habitante
	WHERE PATERNO LIKE 'CARDENAS' AND Materno LIKE 'AQUINO'