-- FUNCIONES CREADAS POR EL USUARIO
CREATE FUNCTION CANTIDAD_CARACTERES(
@CADENA VARCHAR(MAX)
)
	RETURNS VARCHAR(MAX)
AS
BEGIN
	RETURN LEN(@CADENA);
END

-- 
DECLARE @TEXTO VARCHAR(30) ='JUAN';
SELECT CANTIDAD_CARACTERES('SDSD')
GO
CREATE FUNCTION sal()
RETURNS VARCHAR(MAX)
AS
BEGIN
	RETURN  'HOLA MUNDO';
END

SELECT DBO.CANTIDAD_CARACTERES('GFGF');
